---
title: "F1 Driver of the Day EDA"
author: "Kathryn DeWitt"
date: "2022-08-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)

rm(list = ls())
set.seed(3636)
```

## Read in the data

```{r read_in}
# @FUNCTION: read_in
# read in the data using a filepath, returns a dataframe
# @param filename = filepath for pc
read_in <- function(filename){
  dataset = read.csv(filename)
  dataset
}


# Read in the kaggle datasets
dsnames <- c("circuits",
             "constructor_results",
             "constructors",
             "driver_standings",
             "drivers",
             "lap_times",
             "pit_stops",
             "qualifying",
             "races",
             "results",
             "seasons",
             "sprint_results",
             "status" )

list_of_df <- list()

for (dsname in dsnames) {
  print(paste("Reading in", dsname))
  list_of_df[[dsname]] <-  read_in(paste0('../data/Kaggle_DS/', dsname, '.csv'))
  print(summary(list_of_df[[dsname]]))
}

# Read in outcome variables for driver of the day, which is an exception in 
#location and naming
dsname <- "driver_of_day"
print(paste("Reading in", dsname))
list_of_df[[dsname]] <-  read_in(paste0('../data/DriverOfDay.csv'))
summary(list_of_df[[dsname]])
```


## Code to combine datasets

### Driver Level Join

```{r create_driver_level_ds}
# FUNCTION create_driver_level_ds
# Creates a driver level dataset by combining Driver of the Day with Driver Data 
# if it's not already in memory
# @returns a dataframe where the PK is driverRef (usually driver's last name, all lower)

create_driver_level_ds <- function(){
  if (! exists("eda_driver_level")) {
      #1. create a modified version of Driver of the day with some driver reference updates
      driverofday_m <- list_of_df[["driver_of_day"]]
      driverofday_m$Driver.of.The.Day[driverofday_m$Driver.of.The.Day=="Verstappen"] <- c("max_verstappen")
      driverofday_m$Driver.of.The.Day[driverofday_m$Driver.of.The.Day=="Kyvat"] <- c("kvyat") #spelling error that needs to be fixed
      driverofday_m$Driver.of.The.Day[driverofday_m$Driver.of.The.Day=="Magnussen"] <- c("kevin_magnussen")
      
      #2. Lower case everything for joins
      driverofday_m$Driver.of.The.Day <- tolower(driverofday_m$Driver.of.The.Day)
      
      #3. Left join the kaggle dataset Drivers using driver ref
      eda_driver_level <- driverofday_m %>% left_join(list_of_df[["drivers"]], by = c("Driver.of.The.Day" = "driverRef"))
      
      #4. clean up and format
      remove(driverofday_m)
      
      #drop unneeded variables 
      eda_driver_level <- eda_driver_level[, !(names(eda_driver_level) %in% c("number", "code", "forename", "surname", "url"))]
      
      #Reformat variables
      eda_driver_level$Race <- as.factor(eda_driver_level$Race)
      eda_driver_level$nationality <- as.factor(eda_driver_level$nationality)
      eda_driver_level$Driver.of.The.Day <- as.factor(eda_driver_level$Driver.of.The.Day)
      
      #Tranlsate DOB to date format
      eda_driver_level$dob <- as.Date(eda_driver_level$dob, "%Y-%m-%d")
      
      #5. return df
      eda_driver_level
  }
  else {
    eda_driver_level
  }
  
}

eda_driver_level <- create_driver_level_ds()

```

There's another variable needed for race level dataset, the number of pit stops

```{r}
#Create a df of number of pitstops per race
pit_stops <- list_of_df[["pit_stops"]]

pit_stops_driver_race <- pit_stops %>% group_by(raceId, driverId) %>% summarise(num_stops = n())

#QA: Verify case between datasets
nrow(pit_stops[c(pit_stops$raceId == 841 & pit_stops$driverId == 153),]) ==
  pit_stops_driver_race$numStops[pit_stops_driver_race$raceId == 841 & pit_stops_driver_race$driverId == 153]

```


```{r}

#TODO: make this into a function as well.

create_race_level_ds <- function(){
  if (! exists("eda_driver_level")) {
    eda_driver_level <- create_driver_level_ds()
  }
  
   if (! exists("eda_race_level")) {
     #create datset
     #Join to race level dataset based on race/year
    eda_race_level <- eda_driver_level %>% left_join(list_of_df[["races"]], by = c("Race" = "name", "Season" = "year"))
    
    #drop unneeded variables 
    eda_race_level <- eda_race_level[, !(names(eda_race_level) %in% c("round", "url"))]
          
    
    #Translate date to date
    eda_race_level$date <- as.Date(eda_race_level$date, "%d/%m/%y")
    eda_race_level$dob <- as.Date(eda_race_level$dob, "%Y-%m-%d")
    
    #NEW VAR: Create age at race
    eda_race_level$age_at_race <- as.numeric(floor((eda_race_level$date - eda_race_level$dob) / 365.25))
    
    #NEW VAR: afternoon race?
    eda_race_level$afternoon_race <-  strptime(eda_race_level$time, "%H:%M:%S") >=  strptime("12:00:00", "%H:%M:%S")
    #TODO: do all these times make sense? some are at 5:10 or 6:00, which is way too early...
    #TODO: are they in track time or local time?
    
    #Join with drivers_standings on driverId + raceId 
    driver_standings <-list_of_df[["driver_standings"]]
    eda_race_level <- eda_race_level %>% left_join(driver_standings, by = c("raceId", "driverId"))
    #TODO: any cols to drop?

    #Join pit_stops_driver race on driverId + raceID to bring in Number of Stops
    eda_race_level <- eda_race_level %>% left_join(pit_stops_driver_race, by = c("raceId", "driverId"))

   }
  else{
    eda_race_level
  }

}


#Variables to create

#TODO: how Tire pattern/usage?
#TODO: race result? Grid starting? status? - results
#TODO: constructor cup winner? - constructors -> constructor_results

eda_race_level <- create_race_level_ds()
summary(eda_race_level)

#Q: Why do we have NA's in this dataset?
eda_race_level[is.na(eda_race_level$points),]
#A: The NA's are due to when we pulled Kaggle vs the most recent driver of the day.
```


## Begin EDA

### Driver Level Checks

```{r}
#reformat data to be factors
summary(eda_driver_level)
eda_driver_level$driverId <- as.factor(eda_driver_level$driverId)
eda_driver_level$Season <- as.factor(eda_driver_level$Season)

summary(eda_driver_level)
#EDA: can we look at age at time of race? (are younger drivers fan favorites?)
hist(as.numeric(eda_race_level$age_at_race))


#EDA: number of stops?
hist(eda_race_level$num_stops)

#EDA: time of race?
table(eda_race_level$afternoon_race)
```

